---

- name: Configuring index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    backup: yes
  become: yes
  tags: 
    - index

